In [4]:
import numpy as np

def create_polynomial_features(X, degree=2):
    """ Creates the polynomial features
    Args:
        X: A array for the data.
        degree: A integer for the degree of the generated polynomial function.
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

# Ví dụ sử dụng
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
degree = 2

X_poly = create_polynomial_features(X, degree)
print("Input X:")
print(X)
print("\nPolynomial features (degree = 2):")
print(X_poly)

Input X:
[[1 2]
 [2 3]
 [3 4]]

Polynomial features (degree = 2):
[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]
